### ISSUE TITLE
eazypy import issue

### ISSUE THREAD

**Issue by pkaf** [gbrammer/eazy-photoz#1]
I followed the instruction to close threedhst . Afterwards when I did 

import threedhst.eazyPy as eazy 

it returned a "ImportError: No module named aXe2html.sexcat.sextractcat" error. Honestly speaking I find it bit tricky to get my head around threedhst dependency on eazypy. It would have been great if a single pip install kind of command would have been available :).

**Comment by gbrammer** [comment]
@pkaf: I still need to clear out this dependency since [astropy.table](http://docs.astropy.org/en/stable/table/index.html) can do all this and much more, but in the meantime you can download a static version of the aXe2html module here: https://code.google.com/archive/p/threedhst/downloads.  Note that you need aXe2html/aXe2html from that tarfile in your `$PYTHONPATH`, not the base directory.  But you don't need to bother running "setup.py" with it.

**Comment by pkaf** [comment]
Hi Gabe

I was wondering do you have a script (in python) in Github that reads
binary files that EAZY returns?

Thanks,
Prajwal

**Comment by gbrammer** [comment]
@pkaf: You can use the `readEazyBinary` function in [eazyPy.py](https://github.com/gbrammer/threedhst/blob/master/threedhst/eazyPy.py) provided with [threedhst](https://github.com/gbrammer/threedhst/).  Again, sorry that things are mixed around in different places.
